import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// import Sidebar from "@/src/components/Sidebar";
// import Header from "@/src/components/Header";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-slate-50 flex">
        {/* We pass role 1 (Student) for now */}
        {/* <Sidebar role={1} />  */}
        
        <div className="flex-1"> {/* ml-72 creates space for the 64w sidebar + padding */}
          {/* <Header /> */}
          <main className="">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}